name: CloudPanel Python Deployment

on:
  push:
    branches:
      - main  # Cambia a 'master' si es el nombre de tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.SSH_USER }}/htdocs/${{ secrets.DOMAIN_NAME }}
            
            git pull origin main

            uv sync --frozen

            clp-python-app-restart --domain=${{ secrets.DOMAIN_NAME }}